<figure>
  <IMG SRC="https://raw.githubusercontent.com/mbakker7/exploratory_computing_with_python/master/tudelft_logo.png" WIDTH=250 ALIGN="right">
</figure>

# Maximum bending moment on a simply supported bridge

# Example




A 12 m span bridge is modelled as 1D continuous simply supported beam. The bridge is subjected to the axle loads ($A$) of 3-axle vehicle, as shown in the figure bellow. The largest axle load will generally cause the maximum bending bending moment ($M_{max}$) under its location $p$.

<p><img src="https://raw.githubusercontent.com/mike-mendoza/Bivariate_NPBN_workshop_files/main/files_pyhton_book_test/Bridge.png" alt="" style="display: block; margin-left: auto; margin-right: auto;" width="500" height="330" /></p>


For this particular vehicle characteristics, i.e., $A_1 \leq A_3 \leq A_2$ and $ D_2 \leq D_1 \leq a$. $M_{max}$ can be computed as follows:
 

$M_{max} =  R_1 a-A_1D_1$

$R_1 = \frac{\left ( \sum_{i=1}^{3}A_i \right )a}{L}, \; i=\{1,2,3\}$

where $R_1$ is the reaction at the left side of the beam, $L$ the total span length, $A_i$ is the individual axle load $i$, $D_i$ corresponds to the inter-axle distance $i$ and $a$ is the distance at which the point of interest $p$ is located.

For this example, we will use a sample of 100 vehicles corresponding to the 3-axle vehicle type _3C_. The measurements were taken by the Weigh-in-Motion (WIM) system on the federal highway BR-101, located in the south of Brazil, in April 2014. The data collected through WIM system includes type of vehicle, individual axle loads and individual inter-axle distances.  

We will determine: 
* The mean value of $M_{max}$ at the point $p$ of the beam.
* The characteristics of the vehicle that cause the minimum $M_{max}$ at the point $p$ of the beam.  
* The characteristics of the vehicle that cause the maximum $M_{max}$ at the point $p$ of the beam.  



### Solution

* We start by importing numpy and loading the data set. 

    To load the data set with numpy we use ``np.loadtxt()`` using the parameters ``delimiter=","`` to define the character used to separate the values and ``skiprows=1`` to skip the first line.
    
    The first 3 columns of the data set correspond to the axle loads and the remaining columns to the inter-axle distances. 
    The data units are kN for the axle loads and m for the inter-axle distances.

In [16]:
import numpy as np
#loading the data set
data = np.loadtxt("https://raw.githubusercontent.com/mike-mendoza/Bivariate_NPBN_workshop_files/a991bc3d9391a92437af1c3d69ae9fdfe6baf6da/files_pyhton_book_test/V3AX_WIM_BR.csv",
                 delimiter=",",skiprows=1)

# how many rows and columns there are in data?
print(f'The shape of data is {np.shape(data)}. Hence, there are {np.shape(data)[0]} rows and {np.shape(data)[1]} columns in data.\n')

#print the first 5 rows of the data array
print(f' The first 5 rows of the data array are:\n\n {data[0:5,:]}') 


The shape of data is (100, 5). Hence, there are 100 rows and 5 columns in data.

 The first 5 rows of the data array are:

 [[42.1 77.5 65.3  5.1  1.4]
 [48.7 80.1 50.2  5.4  1.2]
 [51.7 90.2 61.6  5.2  1.2]
 [41.2 75.7 58.6  5.4  1.2]
 [25.  48.4 33.5  5.6  1.2]]


* Define the input variables to solve the problem and check if the conditions are satisfied (we will use ``np.all()`` to whether all array elements along a given axis evaluate to ``True``)

In [17]:
# Define the geometric characteristics: the span length (l), the distance (a) at which the point of interest is located.
l = 12      # m
a = 6.07    # m

# Get the axle load and inter-axle distance observations from the loaded data
axle_loads = data[:,0:3] #in kN
inter_axle_distances  = data[:,3:5] # in m

# check if all vehicles meet the requirements: 
# np.all() Test whether all array elements along a given axis evaluate to True
print('Do the characteristics of all vehicles meet the requirements?')
print('Is A2 > A3?', np.all(axle_loads[:,1]>axle_loads[:,2]))  #A2>A3
print('Is A2 > A1?', np.all(axle_loads[:,1]>axle_loads[:,0]))  #A2>A1
print('Is A3 > A2?', np.all(axle_loads[:,2]>axle_loads[:,0]))  #A3>A2
print('Is a > D1?', np.all(a>inter_axle_distances[:,0]))  #a>D1
print('Is D1 > D2?', np.all(inter_axle_distances[:,0]>inter_axle_distances[:,1]),'\n')  #D1>D2


Do the characteristics of all vehicles meet the requirements?
Is A2 > A3? True
Is A2 > A1? True
Is A3 > A2? True
Is a > D1? True
Is D1 > D2? True 



* Use the given equations to compute the $M_{max}$ caused by each one the vehicles in the data.

In [18]:
# reaction at the left side of the beam.
r_1 = (np.sum(axle_loads, axis=1)*a)/l

#Maximum bending bending moments caused for all vehicles at the point $p$ of the beam
m_max = r_1*a-axle_loads[:,0]*inter_axle_distances[:,0]


* Answering the first question: What is the mean value of $M_{max}$ at the point $p$ of the beam.

In [19]:
#The mean value
mean_m_max = np.mean(m_max)
print(f'The mean maximum bending moment is {mean_m_max:.2f}kNm \n')


The mean maximum bending moment is 328.88kNm 



* Answering the second question: What are the characteristics of the vehicle that cause the minimum $M_{max}$ at the point $p$ of the beam?

In [23]:
#The minimum bending moment  
min_m_max = np.min(m_max)

#Find the index of where the min value is located
idx_min_m_max = np.argmin(m_max) 

#Get the characteristics of the vehicle
vehicle_min_m_max = data[idx_min_m_max] 

print(f'The vehicle that causes the min bending moment of {min_m_max:.2f} kNm is the vehicle number {idx_min_m_max}\n'
      f'With axle loads: {vehicle_min_m_max[0:3]} in kN\n'
      f'and inter-axle distances: {vehicle_min_m_max[3:5]} in m \n')

The vehicle that causes the min bending moment of 133.73 kNm is the vehicle number 15
With axle loads: [24.9 39.3 27.2] in kN
and inter-axle distances: [5.9 1.2] in m 



* Answering the second question: What are the characteristics of the vehicle that cause the minimum $M_{max}$ at the point $p$ of the beam?

In [22]:
#The maximum bending moment 
max_m_max = np.max(m_max)

#Find the index of where the max values are located
idx_max_m_max = np.argmax(m_max) 

#Get the characteristics of the vehicle
vehicle_max_m_max = data[idx_max_m_max]

print(f'The vehicle that causes the max bending moment of {max_m_max:.2f} kNm is the vehicle number {idx_max_m_max}\n'
      f'With axle loads: {vehicle_max_m_max[0:3]} in kN\n'
      f'and inter-axle distances: {vehicle_max_m_max[3:5]} in m \n')

The vehicle that causes the max bending moment of 582.44 kNm is the vehicle number 48
With axle loads: [ 62.5 117.7 107.2] in kN
and inter-axle distances: [4.8 1.2] in m 



# Exercise: The biggest truck

Get the largest element of each column of the WIM sample provided above to create the synthetic vehicle _3C Magnus_. Using the same dimensions of the previous described bridge answer the following questions: 


:::{Note}

Here is your **tool box** to solve this exercise:

* Import numpy and load the data set. 
* Define the input variables and check if the conditions are satisfied.
* Get the maxim values of the axle loads and inter-axle distances to create the synthetic vehicle.
* Use the given equations on the example to compute $M_{max}$ caused by the synthetic vehicle.

You can use the following numpy functions (but not limited to): 
``np.loadtxt()``, ``np.all()``, ``np.max()``

:::


In [34]:

from jupyterquiz import display_quiz

display_quiz('quiz_5_1.json')


<IPython.core.display.Javascript object>

In [9]:
max_truck = np.max(data,axis=0)
axle_loads = max_truck[0:3]
inter_axle_distances  = max_truck[3:5] #m

resultant = np.sum(axle_loads)

r_a = (resultant*a)/l

m = r_a*a-axle_loads[0]*inter_axle_distances[0]
print(axle_loads)
print(inter_axle_distances)
print(f'{round(m,1)}')



[ 74.  122.  107.2]
[6.  1.4]
486.9
