<figure>
  <IMG SRC="https://raw.githubusercontent.com/mbakker7/exploratory_computing_with_python/master/tudelft_logo.png" WIDTH=250 ALIGN="right">
</figure>

# Python Notebook #5


# Numpy

The <b><code>numpy</code></b> package is one of the main packages when it comes to working with arrays and matrices in Python, making it indispensable to process and visualize scientific data. Its assortment of routines facilitates operations such as mathematical, logical, linear algebra, Fourier transforms, and much more. In this section, you will learn some of the most used <b><code>numpy</code></b> functions to work with multidimensional array objects.

***

In [1]:
# as always, let's import the package we will use
import numpy as np

***
The following functions will be discussed in this Notebook:
- <b><code>np.array()</code></b> 
- <b><code>np.zeros()</code></b> 
- <b><code>np.asarray()</code></b> 
- <b><code>np.shape()</code></b>
- <b><code>np.min()</code></b>
- <b><code>np.max()</code></b>
- <b><code>np.mean()</code></b>
- <b><code>np.sort()</code></b>
- <b><code>np.linspace()</code></b>
- <b><code>np.arange()</code></b>
- <b><code>np.argmax()</code></b>
- <b><code>np.argmin()</code></b>
- <b><code>np.where()</code></b>
- <b><code>np.astype()</code></b>
- <b><code>np.dot()</code></b>
- <b><code>np.transpose()</code></b>
- <b><code>np.loadtxt()</code></b>
- <b><code>np.sum()</code></b>
- <b><code>np.cos()</code></b>
- <b><code>np.sin()</code></b>
- <b><code>np.sqrt()</code></b>


In Section 2.3, of Notebook 2, you have already encountered lists, which are created with square brackets <b><code>[]</code></b>. Arrays are the <b><code>numpy</code></b> equivalent of lists, with a few characteristic traits:<br><br>- <b><code>numpy</code></b> arrays can only store one type of element,<br>- <b><code>numpy</code></b> arrays take up much less memory than lists,<br>- <b><code>numpy</code></b> arrays have a much better runtime behavior,<br>- it is easier to work with multi-dimensional <b><code>numpy</code></b> arrays than with multi-dimensional lists<br><br>

## 1-Dimensional arrays

### ``np.array()``, ``np.asarray()``
So, how do you create a <b><code>numpy</code></b> 1-Dimensional (1D) array? There are a few ways to do it...

* Option 1 - from scratch with ``np.array()``

In [10]:
# similar to a list
arr1 = np.array([1,2,3])

# Let's check its contents and type
print('arr1 = {}, its type is {}'.format(arr1,type(arr1)))

arr1 = [1 2 3], its type is <class 'numpy.ndarray'>


* Option 2 - from an existing list with ``np.array()``

In [4]:
# create the list first and check its type
L_1 = [1,2,3,5,7,11,13]
print('L_1 = {} and its type is {}\n'.format(L_1,type(L_1)))

# create the array A_1 from the list L_1
# and check its type
A_1 = np.array(L_1)
print('A_1 = {} and its type is {}'.format(A_1, type(A_1)))

L_1 = [1, 2, 3, 5, 7, 11, 13] and its type is <class 'list'>

A_1 = [ 1  2  3  5  7 11 13] and its type is <class 'numpy.ndarray'>


* Option 3 - from an existing list with ``np.asarray()``

In [5]:
# create the list first and check its type
L_1 = [1,2,3,5,7,11,13]
print('L_1 = {} and its type is {}\n'.format(L_1,type(L_1)))

# create the array A_1 from the list L_1
# and check its type
A_1 = np.asarray(L_1)
print('A_1 = {} and its type is {}'.format(A_1, type(A_1)))

L_1 = [1, 2, 3, 5, 7, 11, 13] and its type is <class 'list'>

A_1 = [ 1  2  3  5  7 11 13] and its type is <class 'numpy.ndarray'>


From the above examples, you can't really determine the difference between using <b><code>np.array()</code></b> or <b><code>np.asarray()</code></b>. Nonetheless, there is a very important one, similar to the <b><code>=</code></b> and <b><code>copy</code></b> conundrum discussed in Notebook 4. When generating an array from a list, both functions do pretty much the same. However, when generating an array from another array, their differences stand out.

In [6]:
# First, let's check the ID of arr1
print('arr1 ID is {}'.format(id(arr1)))

arr1 ID is 3116429230896


In [12]:
# Now, let's make two new arrays from arr1, using both functions
arr_array = np.array(arr1)
arr_asarray = np.asarray(arr1)

print('arr_array = {} and its ID is {}\n'.format(arr_array,id(arr_array)))
print('arr_asarray = {} and its ID is {}'.format(arr_asarray, id(arr_asarray)))

arr_array = [100   2   3] and its ID is 3116697984144

arr_asarray = [100   2   3] and its ID is 3116429231184


Hmm... it seems that the ID of <b><code>arr_asarray</code></b> is the same as the original <b><code>arr1</code></b>. Which means they are the same variable! Altering one will alter the other one as well. Let's try it out.

In [13]:
arr1[0] = 'hello'
print(arr_asarray)

ValueError: invalid literal for int() with base 10: 'hello'

Oops... it didn't work. Why do you think it didn't work?

<b>Answer</b>: . . .

In [14]:
# Change the first element of arr1
arr1[0] = 100
# Print arr_array and arr_asarray to see if the first element changed
print('arr1 = {}\n'.format(arr1))
print('arr_array = {}\n'.format(arr_array))
print('arr_asarray = {}'.format(arr_asarray))

arr1 = [100   2   3]

arr_array = [100   2   3]

arr_asarray = [100   2   3]


Yep, our theory was right: <b><code>arr1</code></b> and <b><code>arr_asarray</code></b> are indeed the same (but <b><code>arr_array</code></b> is not!). Therefore, altering <b><code>arr1[0]</code></b> will alter <b><code>arr_asarray[0]</code></b> in the same way.

In [15]:
# final check that they are indeed the same
print(arr1 is arr_asarray)

True


### ``np.zeros()``
In case you already know the size of the array you will need, it is common to initialize it with zeros first using the <code>np.zeros()</code> function, as shown below.

In [21]:
np.set_printoptions(threshold=1) # ignore this line
# its purpose is to set a limit when printing the huge arrays we will generate

In [18]:
# eg: I know I will need an array with 100000 elements
# so I create it full of zeros first
my_arr = np.zeros(100000)
print('my_arr with a bunch of zeros \n{}\n'.format(my_arr))
print('#######################')

# then, I assign the values I need to each element..
# here, in this example, I only wrote a for loop to assign random
# integer numbers between 0 and 9 to it

import random

for i in range(len(my_arr)): # note the use of range(len(my_arr)), we use this often to specify the range
                             # of the for loop to be of the same size as some array
    my_arr[i] = random.randint(0,9)
    
print('\nmy_arr with random numbers \n{}'.format(my_arr))


my_arr with a bunch of zeros 
[0. 0. 0. ... 0. 0. 0.]

#######################

my_arr with random numbers 
[1. 0. 9. ... 7. 2. 4.]


Note that these arrays still have $100000$ elements, but due to our first line of code we truncated the print function to not print it completely — otherwise you would have to scroll a lot. :P 

### ``np.min()``, ``np.max()`` and ``np.mean()``

Numpy also provides various packages to help you process your data. You can, for instance, find out what is the minimum value of an array, or its mean. Your task is to find the minimum, maximum, and mean values of an array.

In [26]:
#Find the minimum, maximum and mean values of A_1
A_1_min = np.min(A_1)
A_1_max = np.max(A_1)
A_1_mean = np.mean(A_1)

# Print your results..
print(f'The minimum value of A_1 is {A_1_min} \n')
print(f'The maximum value of A_1 is {A_1_max} \n')
print(f'The mean value of A_1 is {A_1_mean} \n')


The minimum value of A_1 is 1 

The maximum value of A_1 is 13 

The mean value of A_1 is 6.0 



### ``np.arange()``

Another useful function of the <b><code>numpy</code></b> module is <b><code>np.arange()</code></b>. First, let's see in the documentation what it does.

It reads:<br><br><i><code>arange([start,] stop[, step,], dtype=None, *, like=None)<br><br>Return evenly spaced values within a given interval.</code></i><br><br>To make a number range you need to choose: <br>1) the starting point,<br>2) the endpoint,<br>3) the interval between each point<br><br>The reason why it reads <b><code>[start,] stop[, step,]</code></b> with square brackets, is that the <b><code>start</code></b> and the <b><code>step</code></b> can be omitted. If not specified, <b><code>start = 0</code></b> and <b><code>step = 1</code></b>, by default.

::: {warning}
Your endpoint is <b>not</b> included in the array. If you want to include the endpoint in the array, you have to specify the stop to be <b>endpoint + step</b>. This will be clearer in the following examples.
:::

In [ ]:
arr = np.arange(5) #omitted start and step
print('arr =', arr)

arr = [0 1 2 3 4]


As mentioned, the endpoint (5) is omitted. If you would like to include it:

In [ ]:
arr = np.arange(5 + 1)
print('arr =', arr)

arr = [0 1 2 3 4 5]


Now, without omiting `start` nor `step`.

In [ ]:
arr = np.arange(1, 2, 0.01) # without endpoint
print('arr =', arr)

arr = [1.   1.01 1.02 ... 1.97 1.98 1.99]


In [ ]:
arr = np.arange(1, 2 + 0.01, 0.01) # including endpoint
print('arr =', arr)

arr = [1.   1.01 1.02 ... 1.98 1.99 2.  ]


You can also generate a descending array, by using negative steps

In [ ]:
arr = np.arange(10,0,-1)
print('arr =', arr)

arr = [10  9  8 ...  3  2  1]


### ``np.sort()``

You can also sort an array in the crescent order using <b><code>np.sort()</code></b>

In [ ]:
sorted_arr = np.sort(arr)
print('sorted_arr =', sorted_arr)

sorted_arr = [ 1  2  3 ...  8  9 10]


### Exercise 5.1.5

Search the functionalities of the <code>np.linspace()</code> function, and generate an array that starts in $-6$, ends in $18$, and has a step of $0.2$.

In [55]:
'''write your code on the dots, DO NOT CHANGE THE NAME OF THE VARIABLES!'''

linspace_range = ...

###BEGIN SOLUTION TEMPLATE=
linspace_range = np.linspace(-6,18,121)
###END SOLUTION


In [56]:
###BEGIN HIDDEN TESTS
assert np.sum(np.abs(linspace_range - np.linspace(-6,18,121))) <= 1e-6, '5.1.5 - Incorrect answer'
###END HIDDEN TESTS

### ``np.sum()``

As the name clearly states, <b><code>np.sum()</code></b> returns the sum of an array. Let's try it out:

In [54]:
arr = ([1,2,3])
my_sum = np.sum(arr)
print(f'The sum of the array is {my_sum}')

The sum of the array is 6


### Exercise 5.1.8

Euler proposed that $\pi$ can be approximated by: 

\begin{equation}
\pi \approx \sqrt{6 \sum_{k=1}^\infty \frac{1}{k^2}}
\end{equation}

Since we do not have $\infty$ in Python, let's assume the upper limit of the summation to be $1000$, instead of $\infty$ Your task is to write a program that computes $\pi$, using the above-proposed method, and prints the results with 5 decimal places. 

In [57]:
# write your code here
k = ... # create an array with values in the interval [1,1000]
fac = 1 / k**2
sum_fac = ...
pi_app = ...

###BEGIN SOLUTION TEMPLATE=
k = np.arange(1, 1001, 1) # create an array with values in the interval [1,1000]
fac = 1 / k**2
sum_fac = np.sum(fac)
pi_app = np.sqrt(6 * sum_fac)

###END SOLUTION

print(pi_app)

TypeError: unsupported operand type(s) for ** or pow(): 'ellipsis' and 'int'

In [ ]:
###BEGIN HIDDEN TESTS
assert abs(pi_app - 3.14063805) <= 1e-6, '5.1.8 - Incorrect answer'
###END HIDDEN TESTS

## 2-Dimensional arrays and matrices

As mentioned earlier, <code><b>numpy</b></code> is not solely built for 1D arrays $-$ it's built to work with multidimensional arrays! So, let's hop into 2D arrays and matrices, which you have already encountered in Linear Algebra. You can construct your own matrix using the <b><code>np.array()</code></b> function, as shown below.

:::{note}
A matrix is strictly 2D. Furthermore, a 2D array is not the same as a 2D matrix. While a matrix is a 2D array, a 2D array is **not** a matrix, per se. 
:::


In [30]:
# let's create a matrix
my_mat1 = np.array([[2,2],[2,2]])
print('my_mat1 is \n{}\nand its type is {}'.format(my_mat1,type(my_mat1)))

my_mat1 is 
[[2 2]
 [2 2]]
and its type is <class 'numpy.ndarray'>


In [31]:
# let's create a second matrix so we can 
# do some operations with my_mat1
my_mat2 = np.array([[1,0],[2,1]])

In [32]:
# now let's multiply my_mat2 x my_mat1
print('my_mat2 * my_mat1 is: \n{}'.format(my_mat2 * my_mat1))
print('\n###########\n')

# let's also multiply my_mat x my_mat2 (changed order)
print('my_mat1 * my_mat2 is: \n{}'.format(my_mat1 * my_mat2))

my_mat2 * my_mat1 is: 
[[2 0]
 [4 2]]

###########

my_mat1 * my_mat2 is: 
[[2 0]
 [4 2]]


### ``np.dot()``

Ok, this is not as expected. As you have seen in Linear Algebra, changing the order of the products <b>affects</b> the final result, when multiplying matrices. You may also check the result by calculating the matrix products by hand. What actually happened, is that Python performed an <b>element-wise</b> multiplication... But, what if you would like to apply matrix multiplication? We will show three options for that.

* Option 1 - ``np.dot(arr1 ,  arr2)``

In [33]:
# np.dot(my_mat2 , my_mat1)
print('np.dot(my_mat2 , my_mat1) is: \n{}'.format(np.dot(my_mat2 , my_mat1)))

print('\n###########\n')

# np.dot(my_mat1 , my_mat2)
print('np.dot(my_mat1 , my_mat2) is:\n{}'.format(np.dot(my_mat1 , my_mat2)))


np.dot(my_mat2 , my_mat1) is: 
[[2 2]
 [6 6]]

###########

np.dot(my_mat1 , my_mat2) is:
[[6 2]
 [6 2]]


Check the answers with the results you got when calculating by hand! This is better, isn't it?

* Option 2 - ``arr1.dot(arr2)``

In [34]:
# my_mat2.dot(my_mat1)
print('my_mat2.dot(my_mat1) is:\n{}'.format(my_mat2.dot(my_mat1)))

print('\n###########\n')

# my_mat1.dot(my_mat2)
print('my_mat1.dot(my_mat2) is: \n{}'.format(my_mat1.dot(my_mat2)))


my_mat2.dot(my_mat1) is:
[[2 2]
 [6 6]]

###########

my_mat1.dot(my_mat2) is: 
[[6 2]
 [6 2]]


* Option 3 - ``arr1 @ arr2``

In [35]:
# my_mat2 @ my_mat1
print('my_mat2 @ my_mat1 is:\n{}'.format(my_mat2 @ my_mat1))

print('\n###########\n')

# my_mat1 @ my_mat2
print('my_mat1 @ my_mat2 is: \n{}'.format(my_mat1 @ my_mat2))

my_mat2 @ my_mat1 is:
[[2 2]
 [6 6]]

###########

my_mat1 @ my_mat2 is: 
[[6 2]
 [6 2]]


As you see from the previous examples, there are at least three different ways to multiply 2D arrays in the same way that you would multiply matrices.


Given the matrices $A$, $B$, and $C$ below, calculate $D = AB\ C^{-1}$

$$A = \begin{bmatrix}2 & 3 \\ 4 & 5 \end{bmatrix}$$
$$B = \begin{bmatrix}2 & 1 \\ 1 & 2\end{bmatrix}$$
$$C = \begin{bmatrix}6 & 1 \\ 1 & 1\end{bmatrix}$$


In [37]:
#let's create the matrices A,B, and C
Mat_A = np.array([[2,3],[4,5]])
Mat_B = np.array([[2,1],[1,2]])
Mat_C = np.array([[6,1],[1,1]])


Invert matrix $C$ using ``np.linalg.inv(Mat_C)`` and perform $A\times B\times C_{inverse}$.

In [38]:
#Invert amtrix C
Mat_C_inv = np.linalg.inv(Mat_C)

Mat_D = (Mat_A*Mat_B)*Mat_C_inv
###END SOLUTION
print(Mat_D)

[[ 0.8 -0.6]
 [-0.8 12. ]]


### ``np.shape()``

A very useful tool of the <code>numpy</code> package is the <code>np.shape()</code> function. When dealing with very large arrays, you often need to find out how many elements are in there, or how many rows and columns there are. Your task for this exercise is to find out how many elements there are in <code>random_array</code> and how many rows and columns <code>random_matrix</code> has.

In [ ]:
#how many elements are in  Mat_D
print(f'There are {len(Mat_D)} elements in Mat_D\n')

#how many rows and columns there are Mat_D
print(f'The shape of Mat_D is {np.shape(Mat_D)}. Hence, there are {np.shape(Mat_D)[0]} rows and {np.shape(Mat_D)[1]} columns in Mat_D.\n')

There are 2 elements in Mat_D

The shape of Mat_D is (2, 2). Hence, there are 2 rows and 2 columns in Mat_D.



Ok, now let's create a 2D array and play with it a bit, to show more functionalities of the <b><code>numpy</code></b> module...

In [ ]:
# generating a 10x11 array (10 rows, 11 columns)
arr = np.zeros([10,11])
np.set_printoptions(threshold=1000) # ignore, just making sure we see the entire array this time
print(arr)

In [ ]:
# now let's give it the vaules 0,1,2,3,...,109:
cnt = 0
for i in range(len(arr)):
    for j in range (len(arr[0])): # since a 2D numpy array is ALWAYS regular, all rows have the
        arr[i,j] = cnt            # same number of elements, which, in turn, is the number of columns
        cnt+=1
        
print(arr)


### Conditions within arrays

Similar to what you've seen in Notebook 2, you can also use conditions to check for values within an array. Let's say you want to select the elements within <b><code>arr</code></b> that are bigger than $100$:

In [74]:
arr = np.array([[60,70],[200,300],[1,2],[40,45]])
arr[arr>100]

array([200, 300])

If you want to know how many elements those are, you can simply check the length:

In [75]:
len(arr[arr>100])

2

Now, instead of counting how many elements are bigger than $100$, let's say you want to set all values bigger than $100$ to be $0$. You could do the following:

In [76]:
arr[arr>100] = 0
print(arr)

[[60 70]
 [ 0  0]
 [ 1  2]
 [40 45]]


You can also include multiple conditions... say you want to change all values between $(50,80)$ to be $-1$, then:

In [77]:
arr[(arr>50) & (arr<80)] = -1 # note that the & means AND, so both conditions must apply
print(arr)

[[-1 -1]
 [ 0  0]
 [ 1  2]
 [40 45]]


Say you want to change all values between $[0,10]$ or values between $[40,50)$, to $1$. Then:

In [78]:
arr[((arr>=0) & (arr<=10)) | (arr>=40) & (arr<50)] = 1 
print(arr)

[[-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]]


::: {note}
* The notation $[40,50)$ means every value between $40$ and $50$, including $40$ but excluding $50$; similar to $(40 \leq value < 50)$.
* The notation <b><code>&</code></b> means <i>'and'</i>, the notation <b><code>|</code></b> means <i>'or'</i>.
:::

### ``np.where()`` and ``np.astype()``

Another useful way to modify values within your array is using the <b><code>np.where()</code></b> function. Let's see how it works.

In [81]:
# resetting `arr` 
arr = np.zeros([10,11])

cnt = 0
for i in range(len(arr)):
    for j in range (len(arr[0])): 
        arr[i,j] = cnt            
        cnt+=1
        
# testing np.where

arr2 = np.where(arr>50)
print(type(arr2))

<class 'tuple'>



Ok, so using <b><code>np.where()</code></b> returns a tuple. Let's transform it into an array, check its shape, and its elements.

In [80]:
arr2 = np.array(arr2)
print(arr2.shape)
print('\n\n------------')
print(arr2)

(2, 59)


------------
[[ 4  4  4 ...  9  9  9]
 [ 7  8  9 ...  8  9 10]]


Ok.. so it looks like <b><code>np.where()</code></b> returned a tuple with the index values where <b><code>arr > 50</code></b>. For instance, the first element of each row of <b><code>arr2</code></b> is the first position where <b><code>arr > 50</code></b>, so <b><code>arr[4][7]</code></b> should return $51$. Let's try it out.

In [82]:
arr[4][7]

51.0

Indeed that's how <b><code>np.where()</code></b> works. It also has similar functionality to the one we described above with <b><code>arr[arr>100] = 0</code></b>. Like this:

In [83]:
new_arr = np.where(arr>100,0,arr)
print(new_arr)

[[  0.   1.   2. ...   8.   9.  10.]
 [ 11.  12.  13. ...  19.  20.  21.]
 [ 22.  23.  24. ...  30.  31.  32.]
 ...
 [ 77.  78.  79. ...  85.  86.  87.]
 [ 88.  89.  90. ...  96.  97.  98.]
 [ 99. 100.   0. ...   0.   0.   0.]]


So, <b><code>np.where()</code></b> can be used in two ways. Either to return a tuple with the index of values that fall under the specified condition; or, to return a modified array following the specified condition.<br><Br> In the above case, <b><code>new_arr = np.where(arr>100,0,arr)</code></b> reads: <b>where</b> arr>100, <b>return</b> 0, <b>otherwise</b> return arr

Lastly, we can change the type of variables within an array with the <b><code>np.astype()</code></b> function. Below a quick example:

In [84]:
arr_float = np.array([1.12,2.5,3.8], dtype='float') # creating an array of floats
print(arr_float)

[1.12 2.5  3.8 ]


In [85]:
arr_int = arr_float.astype(int)
print(arr_int)

[1 2 3]


Well.. apparently it worked, all numbers have been rounded down to their closer integer.

### ``np.argmax()`` and ``np.argmin()``

Other functions that assist you in localizing some values within an array are the <b><code>np.argmax()</code></b> and <b><code>np.argmin()</code></b> functions. As the name states, they return the first index with the max (or min) value. Let's check some quick examples:

In [86]:
print(np.argmin(arr),np.argmax(arr))

0 109


No surprises there.. the index where <code>arr</code> has its minimum value is $0$, and it has its maximum at $109$. Below an example of how these functions might be useful:

Say you have an array with the maximum temperature of each month in the NL, and you would like to know which month had the temperature closest to $15$ degrees.

In [87]:
temp_NL = np.array([3.1,3.3,6.2,9.2,13.1,15.6,17.9,17.5,14.5,10.7,6.7,3.7]) # list of temp, per month

You can use the `abs()` and `np.argmin()` functions to find out which month had the temperature closest to $15$ degrees.

In [88]:
dif_arr = abs(temp_NL - 15) # array with the monthly (absolute) deviations from 15 degrees, 
                            # now you only need to find where this
                            # deviation was the smallest using np.argmin()
    
min_temp_indx = np.argmin(dif_arr)
print(min_temp_indx)

8


The month with the temperature closest to $15$ was the month with index $8$, which is September. (Recall 0-th based index, therefore index 8 corresponds to the $9^{th}$ month = September).

### ``np.transpose()``

The function <code>np.transpose()</code> is another helpful function. It returns the transpose of an array (or matrix). Below some examples.

In [89]:
# let's generate a (1,10) array with random int numbers between 0 and 100.
x = np.random.randint(100,size = (1,10))
print(x)

[[24 41 12 ... 17 92 24]]


In [90]:
# now, if we transpose the array:
x_transpose = np.transpose(x)
print(x_transpose)

[[24]
 [41]
 [12]
 ...
 [17]
 [92]
 [24]]


In [91]:
# we can also see that the new shape is (10,1)
print(x_transpose.shape)

(10, 1)


Recall the equation <b>$A x = b$</b> from Linear Algebra, with $A$ being an $m$ x $n$ Matrix. Here, $A x$ only exists if  $x$ has an $n$ x $1$ shape. In this scenario, the <b><code>np.transpose()</code></b> could come in handy. Let's look at the below example.

In [92]:
# generating a 10 x 10 matrix
A = np.random.randint(10, size=(10,10))

print(A)

[[0 8 9 ... 0 8 6]
 [2 5 7 ... 0 6 0]
 [2 0 7 ... 3 5 9]
 ...
 [9 0 5 ... 5 4 3]
 [0 9 6 ... 3 7 0]
 [7 1 4 ... 2 1 7]]


In [93]:
# now if we try to perform Ax
b = A@x

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 10)

It gives an error since <b><code>x.shape</code></b> is $1$ x $10$. Now if we try with <b><code>x_tranpose</code></b>...

In [94]:
b = A@x_transpose
print(b)

[[3345]
 [2206]
 [2454]
 ...
 [2848]
 [2723]
 [1595]]


It works! Finally, a quicker way to transpose an array is to use <b><code>.T</code></b>, as shown below

In [95]:
x_tranpose2 = x.T
print(x_tranpose2)

[[24]
 [41]
 [12]
 ...
 [17]
 [92]
 [24]]


### Exercise 5.1.6

In Notebook 2, you were already introduced to <code>for</code> loops. In this exercise, your task is to create a <code>for</code> loop to append integer numbers between $[0,10]$ to the list $A$.

In [17]:
'''Do not change this varible!'''
A = []

# your code here
...

###BEGIN SOLUTION TEMPLATE=
A = []

for i in range(0, 10 + 1):
    A.append(i)
###END SOLUTION

   
print(A)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [18]:
###BEGIN HIDDEN TESTS
assert (A == list(range(11))), '5.1.6 - Incorrect answer'
###END HIDDEN TESTS

### Exercise 5.1.7

An aeroplane is initially flying at a speed of $v_0 = 85 \ m/s$, when it starts accelerating horizontally by exerting a force of $3000 \ N$. An aerospace engineer wants to know its instantaneous speed, every second, for $1$ minute. The equation of air resistance is $F_{\text{air}} = kv^2$ with $k = 0.24  \ \frac{kg}{m}$. The mass of the airplane is $2000 \ kg$.<br><br>From physics we know that,<br><ol><li>$v_i = v_{i-1} + a_{i-1}(t_i-t_{i-1}) =v_{i-1} + a_{i-1}$</li><li>$F_{\text{air},i} = k\cdot v_i^2$</li><li>$F - F_{\text{air},i} = m\cdot a_i$</li></ol><br>where $t_i$ refers to the $i$-th time instant and in our case $t_i-t_{i-1}=1$ s. Your task is to return <code>v</code>, a list containing the speed of the plane at $t = 0 \ s$, $t = 1 \ s$, ..., $t = 60 \ s$. (Therefore, <code>v</code> should have $61$ elements). 

In [5]:
'''Do not change these variables!'''
t = np.arange(0,61,1) # seconds
v = np.zeros(len(t))
v[0] = 85 # m/s
a = 0
m = 2000 # kg
c = 0.24 # kg/m
F = 3000 # N


# # Start your code here
for i in range(1,len(t)):
    v[i] = ...
    F_air = ...
    F_R = ...
    a = ...
    
###BEGIN SOLUTION TEMPLATE=
for i in range(1,len(t)):
    v[i] = v[i-1] + a
    F_air = c * v[i]**2
    F_R = F - F_air
    a = F_R / m
###END SOLUTION

'''Here we will generate a plot to show the results, do not change anything below'''
import matplotlib.pyplot as plt   

fig, ax = plt.subplots()
ax.plot(t,v)
ax.set(ylim = (80,120), xlim = (0,60),
title='Aeroplane speed through 1 min of constant acceleration',
xlabel='time [s]', ylabel = 'speed [m/s]')
plt.show()

TypeError: float() argument must be a string or a number, not 'ellipsis'

In [ ]:
###BEGIN HIDDEN TESTS
v_list_check = []
a = 0
m = 2000 # kg
c = 0.24 # kg/m
F = 3000 # N

for i in range(len(t)):
    if i == 0:
        v_list_check.append(85)
    else:
        v_cur = v_list_check[i-1] + a
        v_list_check.append(v_cur)
        F_air = c*v_list_check[i]**2
        F_R = F-F_air
        a = F_R/m 
        
assert np.sum(np.abs(np.array(v_list_check) - np.array(v))) <= 1e-6, '5.1.7 - Incorrect answer'
###END HIDDEN TESTS

If you have done the exercise correctly, the graph produced should have shown a decrease in the slope of the curve as the airplane keeps accelerating. This is due to the fact that the force produced by the plane is constant while the air resistance is quadratically related to the velocity. Therefore, a higher velocity yields a quadratic increase in air resistance; and, therefore, a smaller acceleration.

Lastly, similar to <b><code>math.cos()</code></b> and <b><code>math.sin()</code></b>, <b><code>numpy</code></b> also has its mathematical functions, such as <b><code>np.cos()</code></b>, <b><code>np.sin()</code></b>, etc.

# Example: Maximum bending moment on a simply supported bridge

A 12 m span bridge is modelled as 1D continuous simply supported beam. The bridge is subjected to the axle loads ($A$) of 3-axle vehicle, as shown in the figure bellow. The largest axle load will generally cause the maximum bending bending moment ($M_{max}$) under its location $p$.

<p><img src="https://raw.githubusercontent.com/mike-mendoza/Bivariate_NPBN_workshop_files/main/files_pyhton_book_test/Bridge.png" alt="" style="display: block; margin-left: auto; margin-right: auto;" width="500" height="330" /></p>


For this particular vehicle characteristics, i.e., $A_1 \leq A_3 \leq A_2$ and $ D_2 \leq D_1 \leq a$. $M_{max}$ can be computed as follows:
 

$M_{max} =  R_1 a-A_1D_1$

$R_1 = \frac{\left ( \sum_{i=1}^{3}A_i \right )a}{L}, \; i=\{1,2,3\}$

where $R_1$ is the reaction at the left side of the beam, $L$ the total span length, $A_i$ is the individual axle load $i$ and $D_i$ corresponds to the inter-axle distance $i$

For this example, we will use a sample of 100 vehicles corresponding to the 3-axle vehicle type _3C_. The measurements were taken by the Weigh-in-Motion (WIM) system on the federal highway BR-101, located in the south of Brazil, in April 2014. The data collected through WIM system includes type of vehicle, individual axle loads and individual inter-axle distances.  

We will determine: 
* The mean value of $M_{max}$ at the point $p$ of the beam.
* The characteristics of the vehicle that cause the minimum $M_{max}$ at the point $p$ of the beam.  
* The characteristics of the vehicle that cause the maximum $M_{max}$ at the point $p$ of the beam.  

To load the data set with numpy we use ``np.loadtxt()`` using the parameters ``delimiter=","`` to define the character used to separate the values and ``skiprows=1`` to skip the first line.

In [35]:
import numpy as np

# We start by defining the span length (l), the distance a and loading the data set. 
l = 12      # m
a = 6.07    # m


data = np.loadtxt("https://raw.githubusercontent.com/mike-mendoza/Bivariate_NPBN_workshop_files/a991bc3d9391a92437af1c3d69ae9fdfe6baf6da/files_pyhton_book_test/V3AX_WIM_BR.csv",
                 delimiter=",",skiprows=1)


#The first 3 columns correspond to the axle loads and the remaining columns to the inter-axle distances. 
#the data units are kN for the axle loads and m for the inter-axle distances

axle_loads = data[:,0:3] #in kN
inter_axle_distances  = data[:,3:5] # in m

# check if all vehicles meet the requirements: 
# np.all() Test whether all array elements along a given axis evaluate to True

print('Do the characteristics of all vehicles meet the requirements?')
print('A2>A3', np.all(axle_loads[:,1]>axle_loads[:,2]))  #A2>A3
print('A2>A1', np.all(axle_loads[:,1]>axle_loads[:,0]))  #A2>A1
print('A3>A2', np.all(axle_loads[:,2]>axle_loads[:,0]))  #A3>A2
print('a>D1', np.all(a>inter_axle_distances[:,0]))  #a>D1
print('D1>D2', np.all(inter_axle_distances[:,0]>inter_axle_distances[:,1]),'\n')  #D1>D2


# reaction at the left side of the beam.
r_1 = (np.sum(axle_loads, axis=1)*a)/l

#Maximum bending bending moments caused for all vehicles at the point $p$ of the beam
m_max = r_1*a-axle_loads[:,0]*inter_axle_distances[:,0]

#The mean value
mean_m_max = np.mean(m_max)

print(f'The mean maximum bending moment is {mean_m_max:.2f}kNm \n')

#The minimum and maximum bending moments  
min_m_max = np.min(m_max)
max_m_max = np.max(m_max)

#Find the index of where the min and max values are located
idx_min_m_max = np.argmin(m_max) 
idx_max_m_max = np.argmax(m_max) 

#Get the characteristics of the vehicles
vehicle_min_m_max = data[idx_min_m_max] 
vehicle_max_m_max = data[idx_max_m_max]

print(f'The vehicle that causes the min bending moment of {min_m_max:.2f} kNm is the vehicle number {idx_min_m_max}\n'
      f'With axle loads: {vehicle_min_m_max[0:3]} in kN\n'
      f'and inter-axle distances: {vehicle_min_m_max[3:5]} in m \n')

print(f'The vehicle that causes the max bending moment of {max_m_max:.2f} kNm is the vehicle number {idx_max_m_max}\n'
      f'With axle loads: {vehicle_max_m_max[0:3]} in kN\n'
      f'and inter-axle distances: {vehicle_max_m_max[3:5]} in m \n')

Do the characteristics of all vehicles meet the requirements?
A2>A3 True
A2>A1 True
A3>A2 True
a>D1 True
D1>D2 True 

The mean maximum bending moment is 328.88kNm 

The vehicle that causes the min bending moment of 133.73 kNm is the vehicle number 15
With axle loads: [24.9 39.3 27.2] in kN
and inter-axle distances: [5.9 1.2] in m 

The vehicle that causes the max bending moment of 582.44 kNm is the vehicle number 48
With axle loads: [ 62.5 117.7 107.2] in kN
and inter-axle distances: [4.8 1.2] in m 



# Exercise: The biggest truck

Get the largest element of each column of the WIM sample provided above to create the synthetic vehicle _3C Magnus_. Using the same dimensions of the previous described bridge answer the following questions: 


In [34]:

from jupyterquiz import display_quiz

display_quiz('quiz_5_1.json')


<IPython.core.display.Javascript object>

In [9]:
max_truck = np.max(data,axis=0)
axle_loads = max_truck[0:3]
inter_axle_distances  = max_truck[3:5] #m

resultant = np.sum(axle_loads)

r_a = (resultant*a)/l

m = r_a*a-axle_loads[0]*inter_axle_distances[0]
print(axle_loads)
print(inter_axle_distances)
print(f'{round(m,1)}')



[ 74.  122.  107.2]
[6.  1.4]
486.9


# After this Notebook 

You should be able to:

- Construct N-dimensional arrays and matrices using `numpy`.
- understand some of the important functions from `numpy`.
